import './globals.css';
import type { Metadata } from 'next';
import HeaderLayout from './components/headerLayout';
import FooterLayout from './components/footerLayout';

export const metadata: Metadata = {
	title: 'prostar App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='ko'>
			<body className='antialiased'>
				<HeaderLayout />
				{children}
				<FooterLayout />
			</body>
		</html>
	);
}
