import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import HeaderLayout from './components/headerLayout';
import FooterLayout from './components/footerLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'prostar App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='ko'>
			<body className={inter.className}>
				<div>
					<HeaderLayout />
					{children}
					<FooterLayout />
				</div>
			</body>
		</html>
	);
}
